= Advent Of Code 2023
:nofooter:

////
Generate html of this readme using asciidoctor (https://docs.asciidoctor.org/asciidoctor/latest/).

The rendered output of this adoc can be generated with the following command:
asciidoctor README.adoc
////

My solutions for the https://adventofcode.com/2023[AoC puzzles 2023]. AoC is a
Christmas themed coding event that takes place each December. Using it to learn
a language or refresh general knowledge is a popular AoC activity.

This year I will solve the problems using one of the following languages each
day e. g. Day 1 => C#, Day 2 => Rust and so on, looping back to C# after Python.

.Languages
- C#
- Rust
- C / C++
- JavaScript
- Java
- Python 

== Solution Overview

y = yes, I solved it, n = no, I didn't solve it, ? = Didn't yet try to solve it

[cols="1,1,1,1"]
|===
| Day | Language | Part 1 | Part 2

| 1
| C#
| Y
| Y

| 2
| Rust
| Y
| Y

| 3
| C++
| Y
| N

| 4
| JavaScript
| Y
| Y

| 5
| Java
| Y
| N

| 6
| Python
| Y
| Y

| 7
| C#
| Y
| ?

| 8
| Rust
| Y
| Y

| 9
| C++
| ?
| ?

| 10
| JavaScript
| ?
| ?

| 11
| Java
| ?
| ?

| 12
| Python
| ?
| ?

| 13
| C#
| ?
| ?

| 14
| Rust
| ?
| ?

| 15
| C++
| ?
| ?

| 16
| JavaScript
| ?
| ?

| 17
| Java
| ?
| ?

| 18
| Python
| ?
| ?

| 19
| C#
| ?
| ?

| 20
| Rust
| ?
| ?

| 21
| C++
| ?
| ?

| 22
| JavaScript
| ?
| ?

| 23
| Java
| ?
| ?

| 24
| Python
| ?
| ?

| 25
| Rust{empty}footnote:[Skipped C# since this is the last day and I like writing rust more.]
| ?
| ?
|===

== Instructions for running

The following sections detail how to run the solutions for each programming
language, because remembering it for all of them is a bit hard.

=== C#

The c# solutions can be run by executing one of the following two commands:

. `cd DayXX.Solutions && dotnet run`
. `dotnet run --project DayXX.Solutions`

:dotnet-8-sdk-url: https://dotnet.microsoft.com/en-us/download/dotnet/8.0

NOTE: An installation of the {dotnet-8-sdk-url}[dotnet 8.0 sdk] is required.

=== Rust

The rust solutions can be run by executing `cargo run` in the project directory.

:rustlang: https://www.rust-lang.org/tools/install

NOTE: An installation of the {rustlang}[rustlang toolchain] is required.

=== C++

The c++ solutions can be build and run by executing the following commands.

[source, console]
....
# Skip if already exists
mkdir build

cd build

# Again skip on additional builds
cmake ..

make
./dayXX/runner
....

NOTE: Requires `cmake > 3.0` and a c\++ toolchain that supports C++20.

=== JavaScript

The javascript solutions can be run by executing `npm i && npm run start` in the
project directories.

:nodejs: https://nodejs.org/en/download

NOTE: Requires an installation of {nodejs}[nodejs] equal to or lather than
version `20.10`.

=== Java

The java solutions can be run by executing `./gradlew(.bat) dayXX:run` where
.bat is only required on windows.

:jdk21: https://jdk.java.net/21/
NOTE: Requires {jdk21}[JDK 21] in the `$PATH`.

=== Python

The python solutions can be run by executing `python3 runner.py` in the project
directories.

NOTE: Requires an installation of python3.

