= Advent Of Code 2023
:nofooter:

////
Generate html of this readme using asciidoctor (https://docs.asciidoctor.org/asciidoctor/latest/).

The rendered output of this adoc can be generated with the following command:
asciidoctor README.adoc
////

My solutions for the https://adventofcode.com/2023[AoC puzzles 2023]. AoC is a
Christmas themed coding event that takes place each December. Using it to learn
a language or refresh general knowledge is a popular AoC activity.

This year I will solve the problems using one of the following languages each
day e. g. Day 1 => C#, Day 2 => Rust and so on, looping back to C# after Python.

.Languages
- C#
- Rust
- C++
- JavaScript
- Java
- Python 

== Solution Overview

[cols="1,1,1,1"]
|===
| Day | Language | Part 1 | Part 2

| 1
| C#
| Y
| Y
|===

== Instructions for running

=== C#

The c# solutions can be run by executing one of the following two commands:

. `cd DayXX.Solutions && dotnet run`
. `dotnet run --project DayXX.Solutions`

:dotnet-8-sdk-url: https://dotnet.microsoft.com/en-us/download/dotnet/8.0

NOTE: An installation of the {dotnet-8-sdk-url}[dotnet 8.0 sdk] is required.

