= Advent Of Code 2023
:nofooter:

////
Generate html of this readme using asciidoctor (https://docs.asciidoctor.org/asciidoctor/latest/).

The rendered output of this adoc can be generated with the following command:
asciidoctor README.adoc
////

My solutions for the https://adventofcode.com/2023[AoC puzzles 2023]. AoC is a
Christmas themed coding event that takes place each December. Using it to learn
a language or refresh general knowledge is a popular AoC activity.

This year I will solve the problems using one of the following languages each
day e. g. Day 1 => C#, Day 2 => Rust and so on, looping back to C# after Python.

.Languages
- C#
- Rust
- C / C++
- JavaScript
- Java
- Python 

== Solution Overview

y = yes, n = no, ? = Skipped for now

[cols="1,1,1,1"]
|===
| Day | Language | Part 1 | Part 2

| 1
| C#
| Y
| Y

| 2
| Rust
| Y
| Y

| 3
| C++
| Y
| N

| 4
| JavaScript
| Y
| Y

| 5
| Java
| ?
| ?

| 6
| Python
| ?
| ?

| 7
| C#
| ?
| ?

| 8
| Rust
| Y
| ?
|===

== Instructions for running

=== C#

The c# solutions can be run by executing one of the following two commands:

. `cd DayXX.Solutions && dotnet run`
. `dotnet run --project DayXX.Solutions`

:dotnet-8-sdk-url: https://dotnet.microsoft.com/en-us/download/dotnet/8.0

NOTE: An installation of the {dotnet-8-sdk-url}[dotnet 8.0 sdk] is required.

=== Rust

The rust solutions can be run by executing `cargo run` in the project directory.

:rustlang: https://www.rust-lang.org/tools/install

NOTE: An installation of the {rustlang}[rustlang toolchain] is required.

=== C++

The c++ solutions can be build and run by executing the following commands.

[source, console]
....
# Skip if already exists
mkdir build

cd build

# Again skip on additional builds
cmake ..

make
./dayXX/runner
....

NOTE: Requires `cmake > 3.0` and a c\++ toolchain that supports C++20.

=== JavaScript

The javascript solutions can be run by executing `npm i && npm run start` in the
project directories.

:nodejs: https://nodejs.org/en/download

NOTE: Requires an installation of {nodejs}[nodejs] equal to or lather than
version `20.10`.

